# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate iconset"
  lane :icons do
    appicon(
      appicon_image_file: 'fastlane/metadata/app_icon.png',
      appicon_devices: %i[ipad iphone ios_marketing],
      appicon_path: 'App/Assets.xcassets'
    )
  end
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "App.xcworkspace", scheme: "App")
    frame_screenshots()
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
  desc "Build a new beta release"
  lane :beta do
    increment_build_number
    build_app(scheme: "App", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end
end
