// Build information, automatically generated by `ng-info`
export const build = {
    version: "0.9.6",
    timestamp: "Mon May 24 2021 14:47:33 GMT+0200 (GMT+02:00)",
    message: null,
    git: {
        user: "dgey",
        branch: "master",
        hash: "53a430",
        fullHash: "53a430426800106508304d19e2a4f6d4c84bc6f1"
    }
};
