# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new internal Build"
  lane :internal do
    gradle(
          task: "assemble",
          build_type: "Release",
          print_command: false,
          properties: {
            "android.injected.signing.store.file" => "/Users/dgey/Desktop/Zertifikate/PlayStoreAppDev",
            "android.injected.signing.store.password" => "ux8nXZ1t2dg0jP",
            "android.injected.signing.key.alias" => "development",
            "android.injected.signing.key.password" => "ux8nXZ1t2dg0jP",
            })
    upload_to_play_store(track: "internal",
                         version_code: 11,
                         version_name: "2.1.0",
                         release_status: "draft",
                         #apk: "path/to/apk.apk",
                         skip_upload_metadata: true,
                         skip_upload_images: true,
                         skip_upload_screenshots: true
                         )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
